FROM python:3.11-slim AS backend

ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc
COPY . /app

RUN pip install -r requirements-dev.txt
EXPOSE 8080

CMD ["python", "manage.py", "runserver", "0.0.0.0:8080"]
