# Generated by Django 5.0.7 on 2025-11-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchResult',
        ),
        migrations.DeleteModel(
            name='MatchSession',
        ),
    ]
