# Generated by Django 5.0.7 on 2025-09-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_content', models.BinaryField()),
                ('filename', models.TextField()),
                ('mime_type', models.TextField()),
                ('content', models.BinaryField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_content', models.BinaryField()),
                ('filename', models.TextField()),
                ('mime_type', models.TextField()),
                ('content', models.BinaryField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
