# Generated by Django 5.0.7 on 2025-09-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_alter_jobdescription_content_alter_resume_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='content',
        ),
    ]
