# Generated by Django 5.0.7 on 2025-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_remove_jobdescription_content_remove_resume_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
