# Generated by Django 5.0.7 on 2025-09-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_alter_jobdescription_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
