# Generated by Django 5.0.7 on 2025-10-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0005_alter_jobdescription_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.IntegerField(help_text='ID của CV từ AI server')),
                ('job_id', models.IntegerField(help_text='ID của JD từ AI server')),
                ('resume_filename', models.CharField(max_length=255)),
                ('match_score', models.FloatField()),
                ('candidate_info', models.JSONField(blank=True, null=True)),
                ('candidate_skills', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description_id', models.IntegerField(help_text='ID của JD từ AI server')),
                ('job_description_filename', models.CharField(help_text='Tên file của JD', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thực hiện')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='overview.matchsession'),
        ),
    ]
